inputs:
  sequences: "data/combined_spike/betacov_spike.fasta"
  metadata: "data/combined_spike/betacov_spike_metadata.tsv"

files:
  final_auspice_file: "betacov_spike.json"
  include: "config/include.txt"
  dropped_strains: "config/dropped_strains.txt"
  reference: "config/betacov_reference.gb"
  auspice_config: "config/auspice_config_betacov_spike.json"
  colors: "config/colors.tsv"
  description: "config/s_description.md"

out_dir: "results_spike"

filter:
  group_by: "virus_species"
  sequences_per_group: 300

